export { default as About } from './about/About'
export { default as Footer } from './footer/Footer'
export { default as Home } from './home/Home'
export { default as Projects } from './projects/Projects'
export { default as Services } from './services/Services'